import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'

import { resolveEdition, type EditionDefinition, type ResolvedEdition } from '@jingwei/module-sdk'

import { discoverModules } from './discovery.js'

const generatedHeader = '// GENERATED by @jingwei/edition-builder. DO NOT EDIT.\n\n'

interface EditionModule {
  readonly default?: EditionDefinition
}

export async function generateEdition(
  repositoryRoot: string,
  editionName: string,
): Promise<ResolvedEdition> {
  const editionPath = join(repositoryRoot, 'editions', `${editionName}.ts`)
  const loaded: unknown = await import(pathToFileURL(editionPath).href)
  if (!isEditionModule(loaded) || loaded.default === undefined) {
    throw new Error(`${editionPath} must export a default EditionDefinition`)
  }

  const discovered = await discoverModules(repositoryRoot)
  const resolved = resolveEdition(
    loaded.default,
    discovered.map(({ manifest }) => manifest),
  )
  const ids = resolved.modules.map(({ manifest }) => manifest.id)
  assertControlPlaneFoundationModules(ids)
  const capabilitySelections = Object.fromEntries(
    resolved.modules.map(({ manifest, enabledCapabilities }) => [
      manifest.id,
      [...enabledCapabilities],
    ]),
  )

  await Promise.all([
    writeGenerated(
      join(repositoryRoot, 'apps/server/src/generated/edition.ts'),
      serverEditionSource(resolved.id, ids, capabilitySelections, loaded.default.navigation),
    ),
    writeGenerated(
      join(repositoryRoot, 'apps/server/src/generated/modules.ts'),
      serverModulesSource(ids),
    ),
    writeGenerated(
      join(repositoryRoot, 'apps/server/src/generated/migrations.ts'),
      migrationsSource(ids),
    ),
    writeGenerated(
      join(repositoryRoot, 'apps/web/src/generated/modules.ts'),
      webModulesSource(ids),
    ),
    writeGenerated(
      join(repositoryRoot, 'apps/web/src/generated/elegant-router.ts'),
      elegantRouterSource(ids),
    ),
    writeGenerated(
      join(repositoryRoot, 'apps/web/src/router/_generated/imports.ts'),
      elegantRouterPlaceholderSource(),
    ),
  ])

  return resolved
}

/** The always-on control plane provisions tenant identity and navigation through these ports. */
export function assertControlPlaneFoundationModules(moduleIds: readonly string[]): void {
  const required = ['iam', 'navigation'] as const
  const missing = required.filter((moduleId) => !moduleIds.includes(moduleId))
  if (missing.length > 0) {
    throw new Error(
      `Edition cannot support the platform control plane without required foundation modules: ${missing.join(', ')}`,
    )
  }
}

function isEditionModule(value: unknown): value is EditionModule {
  return typeof value === 'object' && value !== null && 'default' in value
}

async function writeGenerated(path: string, body: string): Promise<void> {
  const content = generatedHeader + body.trimEnd() + '\n'
  await mkdir(dirname(path), { recursive: true })
  const current = await readFile(path, 'utf8').catch(() => null)
  if (current !== content) await writeFile(path, content, 'utf8')
}

function alias(moduleId: string, suffix: string): string {
  const identifier = moduleId.replaceAll(/-([a-z])/gu, (_, letter: string) => letter.toUpperCase())
  return `${identifier}${suffix}`
}

function serverEditionSource(
  editionId: string,
  moduleIds: readonly string[],
  capabilities: Readonly<Record<string, readonly string[]>>,
  navigation: EditionDefinition['navigation'],
): string {
  const imports = moduleIds
    .map(
      (id) =>
        `import { manifest as ${alias(id, 'Manifest')} } from '@jingwei/module-${id}/manifest'`,
    )
    .join('\n')
  const modules = moduleIds
    .map((id) => {
      const values = capabilities[id] ?? []
      return `    '${id}': { capabilities: ${JSON.stringify(values)} },`
    })
    .join('\n')
  const catalog = moduleIds.map((id) => alias(id, 'Manifest')).join(', ')
  const navigationSource =
    navigation === undefined ? '' : `  navigation: ${JSON.stringify(navigation)},\n`

  return `${imports}\nimport { defineEdition, resolveEdition } from '@jingwei/module-sdk'\n\nconst edition = defineEdition({\n  id: '${editionId}',\n  modules: {\n${modules}\n  },\n${navigationSource}})\n\nexport const generatedEdition = resolveEdition(edition, [${catalog}])\n`
}

export function serverModulesSource(moduleIds: readonly string[]): string {
  const hasOrganization = moduleIds.includes('organization')
  const imports = moduleIds
    .map((id) => {
      if (hasOrganization && id === 'iam') {
        return `import { createIamServerModule } from '@jingwei/module-iam/server'`
      }
      if (id === 'organization') {
        return `import { createOrganizationServerModule } from '@jingwei/module-organization/server'`
      }
      return `import { serverModule as ${alias(id, 'ServerModule')} } from '@jingwei/module-${id}/server'`
    })
    .join('\n')
  const integrationImports = hasOrganization
    ? `\nimport { createOrganizationalScopeFacts } from '@jingwei/module-organization/server/public'`
    : ''
  const modules = moduleIds
    .map((id) => {
      if (hasOrganization && id === 'iam') {
        return `    createIamServerModule({ organizationalScopeFacts }),`
      }
      if (id === 'organization') {
        return `    createOrganizationServerModule({ organizationalScopeFacts }),`
      }
      return `    ${alias(id, 'ServerModule')},`
    })
    .join('\n')
  const facts = hasOrganization
    ? `  const organizationalScopeFacts = createOrganizationalScopeFacts(context.database)\n`
    : `  void context\n`
  return `${imports}${integrationImports}\nimport type { ServerModuleContext } from '@jingwei/module-sdk/server'\n\nexport function createGeneratedServerModules(context: ServerModuleContext) {\n${facts}  return [\n${modules}\n  ] as const\n}\n`
}

export function webModulesSource(moduleIds: readonly string[]): string {
  const hasOrganization = moduleIds.includes('organization')
  const imports = moduleIds
    .map((id) =>
      hasOrganization && id === 'organization'
        ? `import { organizationalScopeReferenceDirectory, webModule as ${alias(id, 'WebModule')} } from '@jingwei/module-organization/web'`
        : `import { webModule as ${alias(id, 'WebModule')} } from '@jingwei/module-${id}/web'`,
    )
    .join('\n')
  const modules = moduleIds.map((id) => `  ${alias(id, 'WebModule')},`).join('\n')
  const integrationImports = hasOrganization
    ? `\nimport { customScopeReferenceDirectoryKey } from '@jingwei/module-iam/public/web'`
    : ''
  const integration = hasOrganization
    ? `  app.provide(customScopeReferenceDirectoryKey, organizationalScopeReferenceDirectory)\n`
    : `  void app\n`
  return `${imports}${integrationImports}\nimport type { App } from 'vue'\n\nexport const generatedWebModules = [\n${modules}\n] as const\n\nexport function installGeneratedWebIntegrations(app: App): void {\n${integration}}\n`
}

export function migrationsSource(moduleIds: readonly string[]): string {
  const platformPackages = ['database', 'tenancy', 'auth', 'audit', 'control-plane', 'outbox']
  const allImports = [
    ...platformPackages.map((id) => ({ specifier: `@jingwei/${id}/migrations`, id })),
    ...moduleIds.map((id) => ({ specifier: `@jingwei/module-${id}/migrations`, id })),
  ]
  const imports = allImports
    .map(
      ({ specifier, id }) =>
        `import { migrations as ${alias(id, 'Migrations')} } from '${specifier}'`,
    )
    .join('\n')
  const spreads = allImports.map(({ id }) => `  ...${alias(id, 'Migrations')},`).join('\n')
  return `${imports}\n\nexport const generatedMigrations = {\n${spreads}\n} as const\n`
}

function elegantRouterSource(moduleIds: readonly string[]): string {
  const pageDirs = moduleIds.map((id) => `  '../../packages/modules/${id}/src/web/pages',`)
  return `export const enabledPageDirs = [\n${pageDirs.join('\n')}\n] as const\n`
}

function elegantRouterPlaceholderSource(): string {
  return `import type { RouteRecordSingleView } from 'vue-router'

// Elegant Router replaces this Edition-safe placeholder during dev/build.
type RawRouteComponent = RouteRecordSingleView['component']

export const layouts: Readonly<Record<string, RawRouteComponent>> = {}
export const views: Readonly<Record<string, RawRouteComponent>> = {}
`
}
