import { createRoute, z } from '@hono/zod-openapi'

import { apiErrorSchema, openApiSecurityNames } from '@jingwei/http-contract'

import {
  accountProfileSchema,
  accountRolesSchema,
  changePasswordInputSchema,
  createIamRoleSchema,
  createManagedUserSchema,
  iamRoleListSchema,
  iamRoleRefSchema,
  iamRoleSchema,
  loginInputSchema,
  loginResultSchema,
  managedUserListSchema,
  managedUserSchema,
  permissionCatalogSchema,
  refreshSessionResultSchema,
  replaceRolePermissionsSchema,
  replaceUserRolesSchema,
  resetManagedUserPasswordSchema,
  rolePermissionListSchema,
  sessionStatusSchema,
  updateAccountInputSchema,
  updateIamRoleSchema,
  updateManagedUserSchema,
  userRoleListSchema,
} from '../../shared/index.js'

const json = <TSchema>(schema: TSchema) => ({
  'application/json': { schema },
})
const error = (description: string) => ({
  description,
  content: json(apiErrorSchema),
})
const authenticated = [{ [openApiSecurityNames.accessTokenCookie]: [] }]
const mutation = [
  {
    [openApiSecurityNames.accessTokenCookie]: [],
    [openApiSecurityNames.csrfHeader]: [],
  },
]
const roleParam = z.object({ roleId: z.uuid() })
const userParam = z.object({ userId: z.uuid() })

export const iamApiRoutes = {
  createSession: createRoute({
    method: 'post',
    path: '/sessions',
    operationId: 'iamCreateSession',
    tags: ['IAM'],
    summary: '登录并创建会话',
    description:
      '验证租户和凭据，创建服务端 opaque token family，并通过 Set-Cookie 写入 HttpOnly Access/Refresh Cookie 与可读的 CSRF Cookie。',
    request: {
      body: {
        required: true,
        content: json(loginInputSchema),
      },
    },
    responses: {
      201: { description: '登录成功', content: json(loginResultSchema) },
      400: error('请求体无效'),
      401: error('凭据无效'),
      403: error('Origin 校验失败'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  getSession: createRoute({
    method: 'get',
    path: '/session',
    operationId: 'iamGetSession',
    tags: ['IAM'],
    summary: '读取当前会话状态',
    description: '未登录也是正常状态，以 authenticated=false 返回，不使用 401 表示匿名。',
    responses: {
      200: { description: '当前会话状态', content: json(sessionStatusSchema) },
      500: error('服务器内部错误'),
    },
  }),
  refreshSession: createRoute({
    method: 'post',
    path: '/sessions/refresh',
    operationId: 'iamRefreshSession',
    tags: ['IAM'],
    summary: '轮换刷新令牌并续期访问令牌',
    description:
      '使用仅发送到本端点的 HttpOnly Refresh Token Cookie 轮换 token family，并重新签发短期 Access Token Cookie。要求 Origin 与双提交 CSRF 校验。',
    security: [
      {
        [openApiSecurityNames.refreshTokenCookie]: [],
        [openApiSecurityNames.csrfHeader]: [],
      },
    ],
    responses: {
      200: { description: '刷新成功', content: json(refreshSessionResultSchema) },
      401: error('刷新令牌无效、过期、已复用或会话已撤销'),
      403: error('Origin 或 CSRF 校验失败'),
      409: error('同一刷新令牌正在被另一个并发请求轮换'),
      500: error('服务器内部错误'),
    },
  }),
  deleteSession: createRoute({
    method: 'delete',
    path: '/sessions/current',
    operationId: 'iamDeleteCurrentSession',
    tags: ['IAM'],
    summary: '退出当前会话',
    security: mutation,
    responses: {
      204: { description: '会话已撤销' },
      401: error('尚未登录'),
      403: error('Origin 或 CSRF 校验失败'),
      500: error('服务器内部错误'),
    },
  }),
  getAccount: createRoute({
    method: 'get',
    path: '/account',
    operationId: 'iamGetAccount',
    tags: ['IAM'],
    summary: '读取当前账号资料',
    description: '始终读取当前会话用户本人的账号投影，不接受调用方指定的用户 id。',
    security: authenticated,
    responses: {
      200: { description: '当前账号资料', content: json(accountProfileSchema) },
      401: error('尚未登录'),
      404: error('账号不可用'),
      500: error('服务器内部错误'),
    },
  }),
  updateAccount: createRoute({
    method: 'patch',
    path: '/account',
    operationId: 'iamUpdateAccount',
    tags: ['IAM'],
    summary: '更新当前账号资料',
    security: mutation,
    request: {
      body: {
        required: true,
        content: json(updateAccountInputSchema),
      },
    },
    responses: {
      200: { description: '更新后的账号资料', content: json(accountProfileSchema) },
      400: error('请求体无效'),
      401: error('尚未登录'),
      403: error('Origin 或 CSRF 校验失败'),
      404: error('账号不可用'),
      500: error('服务器内部错误'),
    },
  }),
  changePassword: createRoute({
    method: 'post',
    path: '/account/password',
    operationId: 'iamChangeAccountPassword',
    tags: ['IAM'],
    summary: '修改当前账号密码',
    description: '校验当前密码后写入新摘要，并撤销该用户全部会话（含当前会话）。',
    security: mutation,
    request: {
      body: {
        required: true,
        content: json(changePasswordInputSchema),
      },
    },
    responses: {
      204: { description: '密码已更新，全部会话已撤销' },
      400: error('请求体无效或当前密码不正确'),
      401: error('尚未登录'),
      403: error('Origin 或 CSRF 校验失败'),
      404: error('账号不可用'),
      500: error('服务器内部错误'),
    },
  }),
  getAccountRoles: createRoute({
    method: 'get',
    path: '/account/roles',
    operationId: 'iamGetAccountRoles',
    tags: ['IAM'],
    summary: '读取当前账号的活跃角色',
    security: authenticated,
    responses: {
      200: { description: '活跃角色列表', content: json(accountRolesSchema) },
      401: error('尚未登录'),
      500: error('服务器内部错误'),
    },
  }),
  listRoles: createRoute({
    method: 'get',
    path: '/roles',
    operationId: 'iamListRoles',
    tags: ['IAM'],
    summary: '读取租户角色列表',
    security: authenticated,
    responses: {
      200: { description: '角色列表', content: json(iamRoleListSchema) },
      401: error('尚未登录'),
      403: error('缺少 iam.role.view 权限'),
      500: error('服务器内部错误'),
    },
  }),
  createRole: createRoute({
    method: 'post',
    path: '/roles',
    operationId: 'iamCreateRole',
    tags: ['IAM'],
    summary: '创建角色',
    description: '角色编码在租户内唯一，创建后不可修改。',
    security: mutation,
    request: {
      body: { required: true, content: json(createIamRoleSchema) },
    },
    responses: {
      201: { description: '已创建的角色', content: json(iamRoleSchema) },
      400: error('请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      409: error('角色编码冲突'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  getRole: createRoute({
    method: 'get',
    path: '/roles/{roleId}',
    operationId: 'iamGetRole',
    tags: ['IAM'],
    summary: '读取角色详情',
    security: authenticated,
    request: { params: roleParam },
    responses: {
      200: { description: '角色详情', content: json(iamRoleSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('缺少 iam.role.view 权限'),
      404: error('角色不存在'),
      500: error('服务器内部错误'),
    },
  }),
  updateRole: createRoute({
    method: 'patch',
    path: '/roles/{roleId}',
    operationId: 'iamUpdateRole',
    tags: ['IAM'],
    summary: '更新角色',
    description: '只允许更新名称、描述和状态；编码不可变。',
    security: mutation,
    request: {
      params: roleParam,
      body: { required: true, content: json(updateIamRoleSchema) },
    },
    responses: {
      200: { description: '更新后的角色', content: json(iamRoleSchema) },
      400: error('路径参数或请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('角色不存在'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  deleteRole: createRoute({
    method: 'delete',
    path: '/roles/{roleId}',
    operationId: 'iamDeleteRole',
    tags: ['IAM'],
    summary: '删除角色',
    description: '系统角色或仍有用户分配的角色不能删除，应改为停用。',
    security: mutation,
    request: { params: roleParam },
    responses: {
      200: { description: '已删除的角色 ID', content: json(iamRoleRefSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('角色不存在'),
      409: error('系统角色或仍有用户分配'),
      500: error('服务器内部错误'),
    },
  }),
  listPermissionCatalog: createRoute({
    method: 'get',
    path: '/permissions',
    operationId: 'iamListPermissionCatalog',
    tags: ['IAM'],
    summary: '读取当前 Edition 可分配权限目录',
    security: authenticated,
    responses: {
      200: { description: '权限目录', content: json(permissionCatalogSchema) },
      401: error('尚未登录'),
      403: error('缺少 iam.role.view 权限'),
      500: error('服务器内部错误'),
    },
  }),
  listRolePermissions: createRoute({
    method: 'get',
    path: '/roles/{roleId}/permissions',
    operationId: 'iamListRolePermissions',
    tags: ['IAM'],
    summary: '读取角色已获授权限',
    security: authenticated,
    request: { params: roleParam },
    responses: {
      200: { description: '角色权限列表', content: json(rolePermissionListSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('缺少 iam.role.view 权限'),
      404: error('角色不存在'),
      500: error('服务器内部错误'),
    },
  }),
  replaceRolePermissions: createRoute({
    method: 'put',
    path: '/roles/{roleId}/permissions',
    operationId: 'iamReplaceRolePermissions',
    tags: ['IAM'],
    summary: '整组替换角色权限',
    description: '权限必须来自当前 Edition；不支持数据范围的权限只能使用 ALL。',
    security: mutation,
    request: {
      params: roleParam,
      body: { required: true, content: json(replaceRolePermissionsSchema) },
    },
    responses: {
      200: { description: '替换后的角色权限', content: json(rolePermissionListSchema) },
      400: error('路径参数、请求体或权限目录无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('角色不存在'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  listUsers: createRoute({
    method: 'get',
    path: '/users',
    operationId: 'iamListUsers',
    tags: ['IAM'],
    summary: '读取租户用户列表',
    security: authenticated,
    responses: {
      200: { description: '用户列表', content: json(managedUserListSchema) },
      401: error('尚未登录'),
      403: error('缺少 iam.user.view 权限'),
      500: error('服务器内部错误'),
    },
  }),
  createUser: createRoute({
    method: 'post',
    path: '/users',
    operationId: 'iamCreateUser',
    tags: ['IAM'],
    summary: '创建用户',
    description: '用户名在租户内唯一；创建时可选初始角色。',
    security: mutation,
    request: {
      body: { required: true, content: json(createManagedUserSchema) },
    },
    responses: {
      201: { description: '已创建的用户', content: json(managedUserSchema) },
      400: error('请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      409: error('用户名或邮箱冲突'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  getUser: createRoute({
    method: 'get',
    path: '/users/{userId}',
    operationId: 'iamGetUser',
    tags: ['IAM'],
    summary: '读取用户详情',
    security: authenticated,
    request: { params: userParam },
    responses: {
      200: { description: '用户详情', content: json(managedUserSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('缺少 iam.user.view 权限'),
      404: error('用户不存在'),
      500: error('服务器内部错误'),
    },
  }),
  updateUser: createRoute({
    method: 'patch',
    path: '/users/{userId}',
    operationId: 'iamUpdateUser',
    tags: ['IAM'],
    summary: '更新用户',
    description: '禁用会撤销该用户全部会话；不能禁用当前登录账号或最后一个管理员。',
    security: mutation,
    request: {
      params: userParam,
      body: { required: true, content: json(updateManagedUserSchema) },
    },
    responses: {
      200: { description: '更新后的用户', content: json(managedUserSchema) },
      400: error('路径参数或请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('用户不存在'),
      409: error('邮箱冲突、禁用自己或最后一个管理员'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  resetUserPassword: createRoute({
    method: 'post',
    path: '/users/{userId}/password',
    operationId: 'iamResetUserPassword',
    tags: ['IAM'],
    summary: '管理员重置用户密码',
    description: '写入新密码摘要并撤销该用户全部会话。',
    security: mutation,
    request: {
      params: userParam,
      body: { required: true, content: json(resetManagedUserPasswordSchema) },
    },
    responses: {
      204: { description: '密码已重置，会话已撤销' },
      400: error('路径参数、请求体无效或账号已禁用'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('用户不存在'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  listUserRoles: createRoute({
    method: 'get',
    path: '/users/{userId}/roles',
    operationId: 'iamListUserRoles',
    tags: ['IAM'],
    summary: '读取用户角色分配',
    security: authenticated,
    request: { params: userParam },
    responses: {
      200: { description: '用户角色列表', content: json(userRoleListSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('缺少 iam.user.view 权限'),
      404: error('用户不存在'),
      500: error('服务器内部错误'),
    },
  }),
  replaceUserRoles: createRoute({
    method: 'put',
    path: '/users/{userId}/roles',
    operationId: 'iamReplaceUserRoles',
    tags: ['IAM'],
    summary: '整组替换用户角色',
    security: mutation,
    request: {
      params: userParam,
      body: { required: true, content: json(replaceUserRolesSchema) },
    },
    responses: {
      200: { description: '替换后的用户角色', content: json(userRoleListSchema) },
      400: error('路径参数、请求体或角色无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('用户或角色不存在'),
      409: error('不能移除最后一个管理员'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
} as const

export const iamOpenApiContract = {
  id: 'iam',
  title: 'IAM',
  basePath: '/iam',
  routes: Object.values(iamApiRoutes),
} as const
