import { z } from '@hono/zod-openapi'

import { apiErrorSchema, openApiSecurityNames } from '@jingwei/http-contract'
import { iamPermissionRequirements } from '@jingwei/module-iam/server/public'
import { createApiRoute, permissionApiAccess } from '@jingwei/module-sdk/server'

import {
  createOrganizationMemberSchema,
  createOrganizationPositionSchema,
  createOrganizationUnitSchema,
  organizationMemberCandidateListSchema,
  organizationMemberListSchema,
  organizationMemberPositionListSchema,
  organizationMemberRefSchema,
  organizationMemberSchema,
  organizationPositionListSchema,
  organizationPositionRefSchema,
  organizationPositionSchema,
  organizationTreeSchema,
  organizationalScopeOptionsSchema,
  organizationUnitRefSchema,
  organizationUnitSchema,
  replaceOrganizationMemberPositionsSchema,
  updateOrganizationMemberSchema,
  updateOrganizationPositionSchema,
  updateOrganizationUnitSchema,
} from '../../shared/index.js'
import { organizationPermissionRequirements } from '../public/permission-requirements.js'

const json = <TSchema>(schema: TSchema) => ({
  'application/json': { schema },
})
const error = (description: string) => ({
  description,
  content: json(apiErrorSchema),
})
const authenticated = [{ [openApiSecurityNames.accessTokenCookie]: [] }]
const mutation = [
  {
    [openApiSecurityNames.accessTokenCookie]: [],
    [openApiSecurityNames.csrfHeader]: [],
  },
]
const unitParam = z.object({ id: z.uuid() })
const unitPositionParam = z.object({ id: z.uuid(), positionId: z.uuid() })
const unitMemberParam = z.object({ id: z.uuid(), userId: z.uuid() })
const viewAccess = permissionApiAccess(organizationPermissionRequirements.view)
const manageAccess = permissionApiAccess(organizationPermissionRequirements.manage)
const scopeOptionsAccess = permissionApiAccess(iamPermissionRequirements.roleManage)

export const organizationApiRoutes = {
  scopeOptions: createApiRoute(scopeOptionsAccess, {
    method: 'get',
    path: '/scope-options',
    operationId: 'organizationListScopeOptions',
    tags: ['Organization'],
    summary: '读取角色授权可选组织',
    description: '返回当前租户全部有效组织，仅供拥有 iam.role.manage 的集中式角色管理员使用。',
    security: authenticated,
    responses: {
      200: { description: '有效组织选项', content: json(organizationalScopeOptionsSchema) },
      401: error('尚未登录'),
      403: error('缺少 iam.role.manage 权限'),
      500: error('服务器内部错误'),
    },
  }),
  tree: createApiRoute(viewAccess, {
    method: 'get',
    path: '/org-units',
    operationId: 'organizationGetTree',
    tags: ['Organization'],
    summary: '读取当前租户组织树',
    description: '返回扁平组织单元列表，客户端按 parentId 组装层级。',
    security: authenticated,
    responses: {
      200: { description: '组织单元列表', content: json(organizationTreeSchema) },
      401: error('尚未登录'),
      403: error('缺少 organization.view 权限'),
      500: error('服务器内部错误'),
    },
  }),
  create: createApiRoute(manageAccess, {
    method: 'post',
    path: '/org-units',
    operationId: 'organizationCreateUnit',
    tags: ['Organization'],
    summary: '创建组织单元',
    security: mutation,
    request: {
      body: { required: true, content: json(createOrganizationUnitSchema) },
    },
    responses: {
      201: { description: '已创建的组织单元', content: json(organizationUnitSchema) },
      400: error('请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('上级组织不存在'),
      409: error('组织编码冲突'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  update: createApiRoute(manageAccess, {
    method: 'patch',
    path: '/org-units/{id}',
    operationId: 'organizationUpdateUnit',
    tags: ['Organization'],
    summary: '更新组织单元',
    description: '可通过 parentId 移动节点；服务端拒绝将节点移动到自身或其后代。',
    security: mutation,
    request: {
      params: unitParam,
      body: { required: true, content: json(updateOrganizationUnitSchema) },
    },
    responses: {
      200: { description: '更新后的组织单元', content: json(organizationUnitSchema) },
      400: error('路径参数或请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('组织或上级组织不存在'),
      409: error('编码冲突或移动成环'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  remove: createApiRoute(manageAccess, {
    method: 'delete',
    path: '/org-units/{id}',
    operationId: 'organizationDeleteUnit',
    tags: ['Organization'],
    summary: '删除组织单元',
    description: '仅允许删除无子节点、无成员、无岗位的空叶子；否则应改为禁用。',
    security: mutation,
    request: { params: unitParam },
    responses: {
      200: { description: '已删除的组织 ID', content: json(organizationUnitRefSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('组织不存在'),
      409: error('仍有子节点、成员或岗位'),
      500: error('服务器内部错误'),
    },
  }),
  listPositions: createApiRoute(viewAccess, {
    method: 'get',
    path: '/org-units/{id}/positions',
    operationId: 'organizationListPositions',
    tags: ['Organization'],
    summary: '读取组织下的岗位',
    security: authenticated,
    request: { params: unitParam },
    responses: {
      200: { description: '岗位列表', content: json(organizationPositionListSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('缺少 organization.view 权限'),
      404: error('组织不存在'),
      500: error('服务器内部错误'),
    },
  }),
  createPosition: createApiRoute(manageAccess, {
    method: 'post',
    path: '/org-units/{id}/positions',
    operationId: 'organizationCreatePosition',
    tags: ['Organization'],
    summary: '在组织下创建岗位',
    security: mutation,
    request: {
      params: unitParam,
      body: { required: true, content: json(createOrganizationPositionSchema) },
    },
    responses: {
      201: { description: '已创建的岗位', content: json(organizationPositionSchema) },
      400: error('路径参数或请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('组织不存在'),
      409: error('岗位编码冲突'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  updatePosition: createApiRoute(manageAccess, {
    method: 'patch',
    path: '/org-units/{id}/positions/{positionId}',
    operationId: 'organizationUpdatePosition',
    tags: ['Organization'],
    summary: '更新岗位',
    security: mutation,
    request: {
      params: unitPositionParam,
      body: { required: true, content: json(updateOrganizationPositionSchema) },
    },
    responses: {
      200: { description: '更新后的岗位', content: json(organizationPositionSchema) },
      400: error('路径参数或请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('岗位不存在'),
      409: error('岗位编码冲突'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  removePosition: createApiRoute(manageAccess, {
    method: 'delete',
    path: '/org-units/{id}/positions/{positionId}',
    operationId: 'organizationDeletePosition',
    tags: ['Organization'],
    summary: '删除岗位',
    description: '仅允许删除无用户占用的岗位；否则应改为停用。',
    security: mutation,
    request: { params: unitPositionParam },
    responses: {
      200: { description: '已删除的岗位 ID', content: json(organizationPositionRefSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('岗位不存在'),
      409: error('仍有用户担任该岗位'),
      500: error('服务器内部错误'),
    },
  }),
  listMembers: createApiRoute(viewAccess, {
    method: 'get',
    path: '/org-units/{id}/members',
    operationId: 'organizationListMembers',
    tags: ['Organization'],
    summary: '读取组织成员',
    description: '返回成员、安全用户投影及其在本组织下的岗位分配。',
    security: authenticated,
    request: { params: unitParam },
    responses: {
      200: { description: '成员列表', content: json(organizationMemberListSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('缺少 organization.view 权限'),
      404: error('组织不存在'),
      500: error('服务器内部错误'),
    },
  }),
  listMemberCandidates: createApiRoute(manageAccess, {
    method: 'get',
    path: '/member-candidates',
    operationId: 'organizationListMemberCandidates',
    tags: ['Organization'],
    summary: '读取可加入组织的候选用户',
    description: '仅返回 ACTIVE 用户的安全投影；不要求 iam.user.view。',
    security: authenticated,
    responses: {
      200: { description: '候选用户列表', content: json(organizationMemberCandidateListSchema) },
      401: error('尚未登录'),
      403: error('缺少 organization.manage 权限'),
      500: error('服务器内部错误'),
    },
  }),
  createMember: createApiRoute(manageAccess, {
    method: 'post',
    path: '/org-units/{id}/members',
    operationId: 'organizationCreateMember',
    tags: ['Organization'],
    summary: '将用户加入组织',
    security: mutation,
    request: {
      params: unitParam,
      body: { required: true, content: json(createOrganizationMemberSchema) },
    },
    responses: {
      201: { description: '已创建的成员归属', content: json(organizationMemberSchema) },
      400: error('路径参数或请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('组织、用户或岗位不存在'),
      409: error('用户已在组织中或主归属冲突'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  updateMember: createApiRoute(manageAccess, {
    method: 'patch',
    path: '/org-units/{id}/members/{userId}',
    operationId: 'organizationUpdateMember',
    tags: ['Organization'],
    summary: '更新组织成员归属',
    security: mutation,
    request: {
      params: unitMemberParam,
      body: { required: true, content: json(updateOrganizationMemberSchema) },
    },
    responses: {
      200: { description: '更新后的成员归属', content: json(organizationMemberSchema) },
      400: error('路径参数或请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('成员不存在'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
  removeMember: createApiRoute(manageAccess, {
    method: 'delete',
    path: '/org-units/{id}/members/{userId}',
    operationId: 'organizationDeleteMember',
    tags: ['Organization'],
    summary: '将用户移出组织',
    description: '会同时解除该用户在本组织下的岗位分配。',
    security: mutation,
    request: { params: unitMemberParam },
    responses: {
      200: { description: '已移除的成员引用', content: json(organizationMemberRefSchema) },
      400: error('路径参数无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('成员不存在'),
      500: error('服务器内部错误'),
    },
  }),
  replaceMemberPositions: createApiRoute(manageAccess, {
    method: 'put',
    path: '/org-units/{id}/members/{userId}/positions',
    operationId: 'organizationReplaceMemberPositions',
    tags: ['Organization'],
    summary: '整组替换成员在本组织的岗位',
    description: '岗位必须属于该组织且启用；同一用户全局只能有一个主岗位。',
    security: mutation,
    request: {
      params: unitMemberParam,
      body: { required: true, content: json(replaceOrganizationMemberPositionsSchema) },
    },
    responses: {
      200: { description: '替换后的岗位列表', content: json(organizationMemberPositionListSchema) },
      400: error('路径参数或请求体无效'),
      401: error('尚未登录'),
      403: error('权限、Origin 或 CSRF 校验失败'),
      404: error('成员或岗位不存在'),
      409: error('重复分配或多个主岗位'),
      415: error('Content-Type 不受支持'),
      500: error('服务器内部错误'),
    },
  }),
} as const

export const organizationOpenApiContract = {
  id: 'organization',
  title: 'Organization',
  basePath: '/organization',
  routes: Object.values(organizationApiRoutes),
} as const
