import { defineModule } from '@jingwei/module-sdk'

export const manifest = defineModule({
  id: 'iam',
  name: '身份与访问管理',
  category: 'foundation',
  dependencies: [],
  optionalDependencies: [],
  capabilities: [
    { id: 'iam.authentication', name: '身份认证' },
    { id: 'iam.authorization', name: '角色与权限' },
  ],
  permissions: [
    { code: 'iam.user.view', name: '查看用户' },
    { code: 'iam.user.manage', name: '管理用户' },
    { code: 'iam.role.view', name: '查看角色' },
    { code: 'iam.role.manage', name: '管理角色' },
  ],
  routeDefinitions: [
    {
      key: 'iam.login',
      page: 'IamLogin',
      layout: 'blank',
      allowedAccessModes: ['PUBLIC'],
      requiredCapability: 'iam.authentication',
    },
    {
      key: 'iam.account',
      page: 'IamAccount',
      layout: 'base',
      allowedAccessModes: ['AUTHENTICATED'],
      requiredCapability: 'iam.authentication',
    },
    {
      key: 'iam.roles',
      page: 'IamRoles',
      layout: 'base',
      allowedAccessModes: ['PERMISSION'],
      requiredCapability: 'iam.authorization',
      requiredPermission: 'iam.role.view',
    },
    {
      key: 'iam.users',
      page: 'IamUsers',
      layout: 'base',
      allowedAccessModes: ['PERMISSION'],
      requiredCapability: 'iam.authentication',
      requiredPermission: 'iam.user.view',
    },
  ],
  navigationItems: [
    {
      code: 'iam.login',
      name: '登录',
      type: 'PAGE',
      parentCode: null,
      routeKey: 'iam.login',
      path: '/signin',
      accessMode: 'PUBLIC',
      sortOrder: 0,
      icon: null,
    },
    {
      code: 'iam.account',
      name: '个人账号',
      type: 'MENU',
      parentCode: 'workspace',
      routeKey: 'iam.account',
      path: '/account',
      accessMode: 'AUTHENTICATED',
      sortOrder: 10,
      icon: 'lucide:user-round',
    },
    {
      code: 'iam.roles',
      name: '角色管理',
      type: 'MENU',
      parentCode: 'administration',
      routeKey: 'iam.roles',
      path: '/iam/roles',
      accessMode: 'PERMISSION',
      sortOrder: 10,
      icon: 'lucide:shield-check',
    },
    {
      code: 'iam.users',
      name: '用户管理',
      type: 'MENU',
      parentCode: 'administration',
      routeKey: 'iam.users',
      path: '/iam/users',
      accessMode: 'PERMISSION',
      sortOrder: 20,
      icon: 'lucide:users',
    },
  ],
})
