export { webModule } from './module.js'
export { activeBrand, setActiveBrand, useActiveBrand } from './state.js'
export { validateEffectiveBrandAssets } from './effective-brand-validation.js'
export { loadEffectiveBrand } from './load-effective-brand.js'
export { platformDefaultFavicon } from './platform-brand.js'
export { default as DefaultBrandMark } from './components/default-brand-mark.vue'
export { default as DefaultBrandWordmark } from './components/default-brand-wordmark.vue'
export { default as BrandLogoAsset } from './components/brand-logo-asset.vue'
